spring:
  application:
    name=easy-traffic-replay

replay:
  methods:
    - com.xh.easy.trafficreplay.service.test.TestAssemble#test01()
    - com.xh.easy.trafficreplay.service.test.TestAssemble#test02(java.lang.String)
    - com.xh.easy.trafficreplay.service.test.TestAssemble#test03(java.lang.String, com.xh.easy.trafficreplay.service.test.Test)