spring:
  application:
    name=easy-traffic-replay

replay:
  methods:
    - com.xh.easy.trafficreplay.service.test.TestAssemble#test01()
    - com.xh.easy.trafficreplay.service.test.TestAssemble#test02(java.lang.String)
    - com.xh.easy.trafficreplay.service.test.TestAssemble#test03(java.lang.String, com.xh.easy.trafficreplay.service.test.Test)
    - com.xh.easy.trafficreplay.service.test.TestAssemble#test04(java.lang.Integer)
    - com.xh.easy.trafficreplay.service.test.TestUtil#test01()
    - com.xh.easy.trafficreplay.service.test.TestUtil#test02(java.lang.String)
    - com.xh.easy.trafficreplay.service.test.TestUtil#test03(java.lang.String, com.xh.easy.trafficreplay.service.test.Test)
    - com.xh.easy.trafficreplay.service.test.TestUtil#test04(java.lang.Integer)
  apollo:
    enabled: false
    key: ass_traffic_replay
    namespace: application